import Link from 'next/link';
import SiteHeader from '@/components/SiteHeader';
import SiteFooter from '@/components/SiteFooter';
import styles from '../site-pages.module.css';

export default function ContactPage(){return <main><SiteHeader />
<section className={styles.hero}><img className={styles.heroImage} src="https://itscovered.co.uk/wp-content/uploads/2021/03/Roath-Church-28x38ft-marquee.jpg" alt="It’s Covered marquee setup"/><div className={styles.heroOverlay}/><div className={`shell ${styles.heroInner}`}><span className={styles.eyebrow}>Contact</span><h1>Let’s talk about your event.</h1><p>If you already know your date, the booking journey is the quickest place to start. If you need a hand first, call or email us directly.</p></div></section>
<section className={styles.section}><div className="shell"><div className={styles.contactGrid}><div className={styles.contactPanel}><span className={styles.label}>Best place to start</span><h2 style={{color:'#19392d',fontSize:'42px',margin:'10px 0 14px'}}>Choose your event date.</h2><p style={{color:'#6d746d',lineHeight:1.7}}>The booking planner collects the details we actually need: date, guest count, layout, postcode, access, marquee choice and extras. That means less back-and-forth before the site visit.</p><Link className="button button-primary button-large" href="/#booking">Start Your Booking →</Link></div><div className={styles.contactCard}><span className={styles.label}>Contact directly</span><a href="tel:07595497491">07595 497491</a><a href="mailto:info@itscovered.co.uk">info@itscovered.co.uk</a><span>Llanellen Court Farm<br/>Abergavenny<br/>NP7 9HT</span><p style={{color:'#6d746d',lineHeight:1.6,margin:0}}>For anything unusual, larger events or questions before you start, just get in touch.</p></div></div></div></section>
<section className={`${styles.section} ${styles.soft}`}><div className="shell"><div className={styles.sectionHead}><div><span className={styles.label}>What happens next</span><h2>Simple online. Properly confirmed in person.</h2></div></div><div className={styles.facts}><div className={styles.fact}><strong>1. Send the basics</strong><span>Choose your date and tell us what you’re planning.</span></div><div className={styles.fact}><strong>2. We review it</strong><span>We check the setup and what needs discussing.</span></div><div className={styles.fact}><strong>3. Site visit</strong><span>Access, measurements, availability and final pricing are confirmed.</span></div></div></div></section>
<SiteFooter /></main>}
