import Link from 'next/link';
import SiteHeader from '@/components/SiteHeader';
import SiteFooter from '@/components/SiteFooter';
import styles from '../site-pages.module.css';

export default function AboutPage(){return <main><SiteHeader />
<section className={styles.hero}><img className={styles.heroImage} src="https://itscovered.co.uk/wp-content/uploads/2021/03/Brilliant-party-Newport.jpg" alt="It’s Covered marquee event"/><div className={styles.heroOverlay}/><div className={`shell ${styles.heroInner}`}><span className={styles.eyebrow}>About It’s Covered</span><h1>Local, experienced and easy to deal with.</h1><p>It’s Covered is a family-run marquee hire company based in Monmouthshire, helping customers create memorable events across South Wales and beyond.</p></div></section>
<section className={styles.section}><div className="shell"><div className={styles.split}><img src="https://itscovered.co.uk/wp-content/uploads/elementor/thumbs/Party-Marquee-Dog-p3meq7elfheddyxmcnbv0jye7qteul968vo36p6qk2.jpg" alt="Marquee party setup"/><div className={styles.copy}><span className={styles.label}>How we work</span><h2>Practical planning, personal service.</h2><p>Marquee hire is about more than putting up a structure. The setup has to work with the venue, the access, the weather, the guest flow and everything else happening on the day.</p><p>That’s why the process starts simple online, then gets confirmed properly with a site visit before anything is final.</p><ul className={styles.checks}><li>Family-run service</li><li>Based in Monmouthshire</li><li>South Wales and beyond</li><li>Professional delivery and setup</li><li>Site visit before final confirmation</li><li>Events of different sizes</li></ul></div></div></div></section>
<section className={`${styles.section} ${styles.soft}`}><div className="shell"><div className={styles.sectionHead}><div><span className={styles.label}>What matters to us</span><h2>Make the process feel easier.</h2><p>The new booking journey is designed to remove guesswork for customers while still leaving room for the proper practical checks that marquee hire needs.</p></div></div><div className={styles.facts}><div className={styles.fact}><strong>Clear communication</strong><span>You should know what happens next and what still needs confirming.</span></div><div className={styles.fact}><strong>Useful recommendations</strong><span>Guest numbers and event plans should lead to sensible marquee options.</span></div><div className={styles.fact}><strong>Proper confirmation</strong><span>The site visit makes sure the final plan works in the real world.</span></div></div></div></section>
<section className={styles.cta}><div className={`shell ${styles.ctaInner}`}><div><h2>Planning something?</h2><p>Start with the date and we’ll guide you from there.</p></div><Link className="button button-light button-large" href="/#booking">Choose Your Date →</Link></div></section>
<SiteFooter /></main>}
