import { notFound } from 'next/navigation';
import Link from 'next/link';
import SiteHeader from '@/components/SiteHeader';
import SiteFooter from '@/components/SiteFooter';
import styles from '../../site-pages.module.css';

const data = {
  'garden-party': { title:'Garden Party', image:'https://itscovered.co.uk/wp-content/uploads/elementor/thumbs/20ftx20ft-Capri-Marquee-pkb3062by5kel22h6auixd0e6vqq4oxb593bn22z8y.jpg', intro:'A beautifully simple Capri setup for smaller garden celebrations and relaxed events.', size:'20ft × 20ft', capacity:'18 seated as standard', price:'£510', includes:['20ft × 20ft Capri marquee','18 chairs','Twinkle lights','3 × 4ft round tables','1 × trestle table','Plain + clear side walls'], ideal:'Birthdays, garden parties, family celebrations and smaller gatherings.' },
  'informal-party': { title:'Informal Party', image:'https://itscovered.co.uk/wp-content/uploads/elementor/thumbs/28x28-Caerleon-p3melmwu7h56y7kk1685e7gq9bc6fk45a9i479ymsy.jpg', intro:'A flexible party setup with room to mingle, eat, drink and celebrate without overcomplicating the layout.', size:'28ft × 28ft or 20ft × 30ft', capacity:'Standing room for 55', price:'£516', includes:['Capri marquee','Standing room for 55','Twinkle lights','Plain + clear side walls'], ideal:'Engagements, birthdays, anniversaries and informal family parties.' },
  'large-party': { title:'Large Party', image:'https://itscovered.co.uk/wp-content/uploads/2021/03/Brilliant-party-Newport.jpg', intro:'More space for bigger guest lists, better flow and a proper party atmosphere.', size:'28ft × 38ft', capacity:'Standing room for 100', price:'£587', includes:['28ft × 38ft Capri marquee','Standing room for 100','Twinkle lights','Plain + clear side walls'], ideal:'Large birthdays, celebrations, drinks-led events and bigger garden parties.' },
  '45-guests': { title:'45 Guests', image:'https://itscovered.co.uk/wp-content/uploads/2023/04/Wedding-Table-Decorations-1.jpg', intro:'A ready-made seated setup for events where dining and guest comfort matter.', size:'20ft × 30ft', capacity:'Up to 45 seated', price:'£1,035', includes:['20ft × 30ft Capri marquee','6 × 4ft round tables','2 × trestle tables','45 chairs','Dandydura matting','Plain + clear side walls'], ideal:'Smaller weddings, seated parties and private dining events.' },
  '80-guests': { title:'80 Guests', image:'https://itscovered.co.uk/wp-content/uploads/elementor/thumbs/Roath-Church-wedding-guests-2-p3mn5mp1l6rj6g6xkazcehi1ih9wl6tvmoxp79anzm.jpg', intro:'A spacious seated package for larger weddings, celebrations and corporate occasions.', size:'28ft × 38ft', capacity:'Up to 80 seated', price:'£1,286', includes:['28ft × 38ft Capri marquee','8 × 5ft round tables','2 × trestle tables','80 chairs','Dandydura matting','Plain + clear side walls'], ideal:'Weddings, milestone events, larger private parties and corporate hospitality.' }
} as const;

export default async function PackagePage({params}:{params:Promise<{package:string}>}){
  const {package:slug}=await params;
  const item=data[slug as keyof typeof data];
  if(!item) notFound();
  const related=Object.entries(data).filter(([key])=>key!==slug).slice(0,3);
  return <main>
    <SiteHeader />
    <section className={styles.hero}><img className={styles.heroImage} src={item.image} alt={`${item.title} Capri marquee`}/><div className={styles.heroOverlay}/><div className={`shell ${styles.heroInner}`}><span className={styles.eyebrow}>Marquee package</span><h1>{item.title}</h1><p>{item.intro}</p><div className={styles.packageHeroMeta}><span>{item.size}</span><span>{item.capacity}</span><span>Site visit before final confirmation</span></div></div></section>
    <section className={styles.section}><div className={`shell ${styles.split}`}><img src={item.image} alt={`${item.title} event setup`}/><div className={styles.copy}><span className={styles.label}>What you get</span><h2>A clear starting point for your event.</h2><div className={styles.packagePrice}>From {item.price}</div><p>{item.ideal}</p><ul className={styles.checks}>{item.includes.map(x=><li key={x}>{x}</li>)}</ul><p className={styles.note}>Package prices shown are current starting prices from the existing It’s Covered package list. Final price and availability will be confirmed after the site visit and once any extras, access requirements and delivery details are known.</p><Link className="button button-primary button-large" href="/#booking">Choose Your Date →</Link></div></div></section>
    <section className={`${styles.section} ${styles.soft}`}><div className="shell"><div className={styles.sectionHead}><div><span className={styles.label}>Make it yours</span><h2>Add only what your event needs.</h2><p>Tables, chairs, flooring, lighting, heating, dance floors, side walls and furniture can all be considered during the booking journey.</p></div></div><div className={styles.facts}><div className={styles.fact}><strong>Layout</strong><span>We tailor the setup around seated, standing or mixed use.</span></div><div className={styles.fact}><strong>Access</strong><span>Van distance, surface and site conditions are confirmed before final pricing.</span></div><div className={styles.fact}><strong>Confirmation</strong><span>Nothing is final until the site visit confirms the practical details.</span></div></div></div></section>
    <section className={styles.section}><div className="shell"><span className={styles.label}>Other packages</span><h2 style={{color:'#19392d'}}>Compare another setup.</h2><div className={styles.related}>{related.map(([key,p])=><Link href={`/packages/${key}`} key={key}>{p.title} →</Link>)}</div></div></section>
    <section className={styles.cta}><div className={`shell ${styles.ctaInner}`}><div><h2>Think this could work?</h2><p>Start with the date and we’ll guide you through the rest.</p></div><Link className="button button-light button-large" href="/#booking">Start Your Enquiry →</Link></div></section>
    <SiteFooter />
  </main>
}
